/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.scientific;

/**
 *
 * @author Ritika
 */
public class scientificcalci extends javax.swing.JFrame {
boolean degrad;
 boolean Shif;
 double firstnum;
 double secondnum;
 String  operations;
double result;
 
    /**
     * Creates new form scientificcalci
     */
    public scientificcalci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnon = new javax.swing.JRadioButton();
        jbtnoff = new javax.swing.JRadioButton();
        jbtnDegree = new javax.swing.JRadioButton();
        jbtnRadian = new javax.swing.JRadioButton();
        jbtnlog = new javax.swing.JButton();
        jbtnlnx = new javax.swing.JButton();
        jbtnsin = new javax.swing.JButton();
        jbtncos = new javax.swing.JButton();
        jbtntan = new javax.swing.JButton();
        jbtnxpower2 = new javax.swing.JButton();
        jbtnxpower3 = new javax.swing.JButton();
        jbtnpie = new javax.swing.JButton();
        jbtnmodulus = new javax.swing.JButton();
        jbtnsinh = new javax.swing.JButton();
        jbtncosh = new javax.swing.JButton();
        jbtntanh = new javax.swing.JButton();
        jbtnxpowery = new javax.swing.JButton();
        jbtnexpo = new javax.swing.JButton();
        jbtnsqroot = new javax.swing.JButton();
        jbtncbr = new javax.swing.JButton();
        jbtnrnd = new javax.swing.JButton();
        jbtnbin = new javax.swing.JButton();
        jbtnoct = new javax.swing.JButton();
        jbtnhex = new javax.swing.JButton();
        jbtnfact = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnplminus = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtndot = new javax.swing.JButton();
        jbtnequal = new javax.swing.JButton();
        jbtnexp = new javax.swing.JButton();
        jbtnplus = new javax.swing.JButton();
        jbtnminus = new javax.swing.JButton();
        jbtnmul = new javax.swing.JButton();
        jbtndiv = new javax.swing.JButton();
        jbtnac = new javax.swing.JButton();
        jbtndel = new javax.swing.JButton();
        jbtnshift = new javax.swing.JButton();
        display2 = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();

        jButton8.setBackground(new java.awt.Color(153, 153, 153));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setText("x^3");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(153, 153, 153));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton15.setText("log");

        jButton22.setBackground(new java.awt.Color(153, 153, 153));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton22.setText("e^x");

        jButton28.setBackground(new java.awt.Color(255, 153, 153));
        jButton28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton28.setText("7");

        jButton32.setBackground(new java.awt.Color(255, 153, 153));
        jButton32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton32.setText("7");

        jButton36.setBackground(new java.awt.Color(255, 153, 153));
        jButton36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton36.setText("3");

        jButton43.setBackground(new java.awt.Color(255, 102, 255));
        jButton43.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton43.setText("+/-");

        jButton46.setBackground(new java.awt.Color(255, 102, 255));
        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton46.setText("+/-");

        jButton49.setBackground(new java.awt.Color(255, 102, 255));
        jButton49.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton49.setText("+/-");

        jButton51.setBackground(new java.awt.Color(255, 102, 255));
        jButton51.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton51.setText("+/-");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel1.setText("scientific calculator");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jbtnon.setBackground(new java.awt.Color(255, 13, 8));
        jbtnon.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnon.setText("ON");
        jbtnon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnonActionPerformed(evt);
            }
        });

        jbtnoff.setBackground(new java.awt.Color(255, 0, 0));
        jbtnoff.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnoff.setText("OFF");
        jbtnoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoffActionPerformed(evt);
            }
        });

        jbtnDegree.setBackground(new java.awt.Color(102, 102, 102));
        jbtnDegree.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnDegree.setText("DEG");
        jbtnDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDegreeActionPerformed(evt);
            }
        });

        jbtnRadian.setBackground(new java.awt.Color(102, 102, 102));
        jbtnRadian.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbtnRadian.setText("RAD");
        jbtnRadian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRadianActionPerformed(evt);
            }
        });

        jbtnlog.setBackground(new java.awt.Color(153, 153, 153));
        jbtnlog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnlog.setText("log");
        jbtnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogActionPerformed(evt);
            }
        });

        jbtnlnx.setBackground(new java.awt.Color(153, 153, 153));
        jbtnlnx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnlnx.setText("Inx");
        jbtnlnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlnxActionPerformed(evt);
            }
        });

        jbtnsin.setBackground(new java.awt.Color(153, 153, 153));
        jbtnsin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnsin.setText("sin");
        jbtnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsinActionPerformed(evt);
            }
        });

        jbtncos.setBackground(new java.awt.Color(153, 153, 153));
        jbtncos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtncos.setText("cos");
        jbtncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncosActionPerformed(evt);
            }
        });

        jbtntan.setBackground(new java.awt.Color(153, 153, 153));
        jbtntan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtntan.setText("tan");
        jbtntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntanActionPerformed(evt);
            }
        });

        jbtnxpower2.setBackground(new java.awt.Color(153, 153, 153));
        jbtnxpower2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnxpower2.setText("x^2");
        jbtnxpower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxpower2ActionPerformed(evt);
            }
        });

        jbtnxpower3.setBackground(new java.awt.Color(153, 153, 153));
        jbtnxpower3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnxpower3.setText("x^3");
        jbtnxpower3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxpower3ActionPerformed(evt);
            }
        });

        jbtnpie.setBackground(new java.awt.Color(153, 153, 153));
        jbtnpie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnpie.setText("₶");
        jbtnpie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpieActionPerformed(evt);
            }
        });

        jbtnmodulus.setBackground(new java.awt.Color(153, 153, 153));
        jbtnmodulus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnmodulus.setText("%");
        jbtnmodulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodulusActionPerformed(evt);
            }
        });

        jbtnsinh.setBackground(new java.awt.Color(153, 153, 153));
        jbtnsinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnsinh.setText("sinh");
        jbtnsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsinhActionPerformed(evt);
            }
        });

        jbtncosh.setBackground(new java.awt.Color(153, 153, 153));
        jbtncosh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtncosh.setText("cosh");
        jbtncosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncoshActionPerformed(evt);
            }
        });

        jbtntanh.setBackground(new java.awt.Color(153, 153, 153));
        jbtntanh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtntanh.setText("tanh");
        jbtntanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntanhActionPerformed(evt);
            }
        });

        jbtnxpowery.setBackground(new java.awt.Color(153, 153, 153));
        jbtnxpowery.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnxpowery.setText("x^y");
        jbtnxpowery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxpoweryActionPerformed(evt);
            }
        });

        jbtnexpo.setBackground(new java.awt.Color(153, 153, 153));
        jbtnexpo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnexpo.setText("e^x");
        jbtnexpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexpoActionPerformed(evt);
            }
        });

        jbtnsqroot.setBackground(new java.awt.Color(153, 153, 153));
        jbtnsqroot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnsqroot.setText("√");
        jbtnsqroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsqrootActionPerformed(evt);
            }
        });

        jbtncbr.setBackground(new java.awt.Color(153, 153, 153));
        jbtncbr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtncbr.setText("Cbr");
        jbtncbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncbrActionPerformed(evt);
            }
        });

        jbtnrnd.setBackground(new java.awt.Color(153, 153, 153));
        jbtnrnd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnrnd.setText("Rnd");
        jbtnrnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrndActionPerformed(evt);
            }
        });

        jbtnbin.setBackground(new java.awt.Color(153, 153, 153));
        jbtnbin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnbin.setText("Bin");
        jbtnbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbinActionPerformed(evt);
            }
        });

        jbtnoct.setBackground(new java.awt.Color(153, 153, 153));
        jbtnoct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnoct.setText("Oct");
        jbtnoct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoctActionPerformed(evt);
            }
        });

        jbtnhex.setBackground(new java.awt.Color(153, 153, 153));
        jbtnhex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnhex.setText("Hex");
        jbtnhex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnhexActionPerformed(evt);
            }
        });

        jbtnfact.setBackground(new java.awt.Color(153, 153, 153));
        jbtnfact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnfact.setText("n!");
        jbtnfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfactActionPerformed(evt);
            }
        });

        jbtn7.setBackground(new java.awt.Color(255, 153, 153));
        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn8.setBackground(new java.awt.Color(255, 153, 153));
        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setBackground(new java.awt.Color(255, 153, 153));
        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn4.setBackground(new java.awt.Color(255, 153, 153));
        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn5.setBackground(new java.awt.Color(255, 153, 153));
        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn6.setBackground(new java.awt.Color(255, 153, 153));
        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn1.setBackground(new java.awt.Color(255, 153, 153));
        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn2.setBackground(new java.awt.Color(255, 153, 153));
        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn3.setBackground(new java.awt.Color(255, 153, 153));
        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnplminus.setBackground(new java.awt.Color(255, 102, 255));
        jbtnplminus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnplminus.setText("+/-");
        jbtnplminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplminusActionPerformed(evt);
            }
        });

        jbtn0.setBackground(new java.awt.Color(255, 153, 153));
        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtndot.setBackground(new java.awt.Color(255, 102, 255));
        jbtndot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtndot.setText(".");
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });

        jbtnequal.setBackground(new java.awt.Color(255, 102, 255));
        jbtnequal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnequal.setText("=");
        jbtnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnequalActionPerformed(evt);
            }
        });

        jbtnexp.setBackground(new java.awt.Color(255, 102, 255));
        jbtnexp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnexp.setText("exp");
        jbtnexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexpActionPerformed(evt);
            }
        });

        jbtnplus.setBackground(new java.awt.Color(255, 102, 255));
        jbtnplus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnplus.setText("+");
        jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusActionPerformed(evt);
            }
        });

        jbtnminus.setBackground(new java.awt.Color(255, 102, 255));
        jbtnminus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnminus.setText("-");
        jbtnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnminusActionPerformed(evt);
            }
        });

        jbtnmul.setBackground(new java.awt.Color(255, 102, 255));
        jbtnmul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnmul.setText("*");
        jbtnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmulActionPerformed(evt);
            }
        });

        jbtndiv.setBackground(new java.awt.Color(255, 102, 255));
        jbtndiv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtndiv.setText("/");
        jbtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivActionPerformed(evt);
            }
        });

        jbtnac.setBackground(new java.awt.Color(255, 0, 0));
        jbtnac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnac.setText("AC");
        jbtnac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnacActionPerformed(evt);
            }
        });

        jbtndel.setBackground(new java.awt.Color(255, 0, 0));
        jbtndel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtndel.setText("DEL");
        jbtndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndelActionPerformed(evt);
            }
        });

        jbtnshift.setBackground(new java.awt.Color(153, 153, 255));
        jbtnshift.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jbtnshift.setText("Shift");
        jbtnshift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnshiftActionPerformed(evt);
            }
        });

        display2.setEditable(false);
        display2.setBackground(new java.awt.Color(255, 255, 51));
        display2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display2ActionPerformed(evt);
            }
        });

        jtxtDisplay.setEditable(false);
        jtxtDisplay.setBackground(new java.awt.Color(51, 153, 255));
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jbtnon, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jbtnpie, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jbtnsqroot, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnoff, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnRadian, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jbtnexp, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(184, 184, 184)
                                                .addComponent(jbtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbtnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(jbtnmodulus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jbtnlnx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jbtncbr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jbtnsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jbtnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                            .addComponent(jbtnrnd, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jbtncosh, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jbtncos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jbtnbin, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(9, 9, 9)
                                                        .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(60, 60, 60)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jbtntanh, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jbtntan, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(jbtnoct, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jbtnxpower2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jbtnxpowery, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(jbtnhex, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jbtnxpower3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jbtnexpo, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                                    .addComponent(jbtnfact, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(302, 302, 302)
                                        .addComponent(jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnshift, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnplminus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbtnac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnmul, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                        .addContainerGap(137, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtDisplay, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(display2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnon)
                    .addComponent(jbtnoff)
                    .addComponent(jbtnDegree)
                    .addComponent(jbtnRadian))
                .addGap(17, 17, 17)
                .addComponent(jbtnshift)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnlog)
                    .addComponent(jbtnlnx)
                    .addComponent(jbtnsin)
                    .addComponent(jbtncos)
                    .addComponent(jbtntan)
                    .addComponent(jbtnxpower2)
                    .addComponent(jbtnxpower3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnpie)
                    .addComponent(jbtnmodulus)
                    .addComponent(jbtnsinh)
                    .addComponent(jbtncosh)
                    .addComponent(jbtntanh)
                    .addComponent(jbtnxpowery)
                    .addComponent(jbtnexpo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnsqroot)
                    .addComponent(jbtncbr)
                    .addComponent(jbtnrnd)
                    .addComponent(jbtnbin)
                    .addComponent(jbtnoct)
                    .addComponent(jbtnhex)
                    .addComponent(jbtnfact))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnac, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnplminus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnexp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoffActionPerformed
        // TODO add your handling code here:
        jbtn0.setEnabled(false);
    jbtn1.setEnabled(false);
    jbtn2.setEnabled(false);
    jbtn3.setEnabled(false);
     jbtn4.setEnabled(false);
    jbtn5.setEnabled(false);
    jbtn6.setEnabled(false);
     jbtn7.setEnabled(false);
     jbtn8.setEnabled(false);
   jbtn9.setEnabled(false);
     jbtnac.setEnabled(false);
     jbtnbin.setEnabled(false);
    jbtncbr.setEnabled(false);
    jbtncos.setEnabled(false);
     jbtncosh.setEnabled(false);
     jbtndel.setEnabled(false);
     jbtndiv.setEnabled(false);
    jbtndot.setEnabled(false);
     jbtnequal.setEnabled(false);
    jbtnexp.setEnabled(false);
    jbtnexp.setEnabled(false);
   jbtnfact.setEnabled(false);
   jbtnhex.setEnabled(false);
     jbtnlnx.setEnabled(false);
   jbtnlog.setEnabled(false);
    jbtnminus.setEnabled(false);
     jbtnmodulus.setEnabled(false);
     jbtnmul.setEnabled(false);
    jbtnoct.setEnabled(false);
    jbtnexpo.setEnabled(false);
     jbtnon.setEnabled(false);
     jbtnpie.setEnabled(false);
     jbtnplminus.setEnabled(false);
     jbtnplus.setEnabled(false);
  jbtnrnd.setEnabled(false);
    jbtnshift.setEnabled(false);
     jbtnsin.setEnabled(false);
    jbtnsinh.setEnabled(false);
     jbtnsqroot.setEnabled(false);
    jbtntan.setEnabled(false);
    jbtntanh.setEnabled(false);
    jbtnxpower2.setEnabled(false);
     jbtnxpower3.setEnabled(false);
     jbtnxpowery.setEnabled(false);
     jbtnDegree.setEnabled(false);
     jbtnRadian.setEnabled(false);
     display2.setEnabled(false);
     jtxtDisplay.setText("");
     display2.setText("");
     
    }//GEN-LAST:event_jbtnoffActionPerformed

    private void jbtntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntanActionPerformed
        // TODO add your handling code here:
         double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        if(!Shif)
        {
            if(!degrad)
            {
                display2.setText("tan("+String.valueOf(ope)+")");
                ope=ope*0.0174532925;
            }
            ope=Math.tan(ope);
        }
        else{
            display2.setText("tan^-1("+String.valueOf(ope)+")");
            ope=Math.atan(ope)/0.0174532925;
        }
        jtxtDisplay.setText(String.valueOf(ope)); 
    }//GEN-LAST:event_jbtntanActionPerformed

    private void jbtnxpower3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxpower3ActionPerformed
        // TODO add your handling code here:
           double ope=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText(String.valueOf(jtxtDisplay.getText())+"^3");
        ope=(ope *ope*ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jbtnxpower3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
         String iNum=jtxtDisplay.getText()+jbtn9.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnshiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnshiftActionPerformed
        // TODO add your handling code here:
        if(!Shif){
            Shif=true;
        }
        else
            Shif=false;
    }//GEN-LAST:event_jbtnshiftActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        String iNum=jtxtDisplay.getText()+jbtn1.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        String iNum=jtxtDisplay.getText()+jbtn0.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
         String iNum=jtxtDisplay.getText()+jbtn2.getText();
        jtxtDisplay.setText(iNum);
        
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
         String iNum=jtxtDisplay.getText()+jbtn3.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
         String iNum=jtxtDisplay.getText()+jbtn4.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
         String iNum=jtxtDisplay.getText()+jbtn5.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
         String iNum=jtxtDisplay.getText()+jbtn6.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:
         String iNum=jtxtDisplay.getText()+jbtn7.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
         String iNum=jtxtDisplay.getText()+jbtn8.getText();
        jtxtDisplay.setText(iNum);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
        // TODO add your handling code here:
        if(!jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText()+jbtndot.getText());
        }
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtnplminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplminusActionPerformed
        // TODO add your handling code here:
        double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ope=ope*(-1);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jbtnplminusActionPerformed

    private void jbtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmulActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("*");
        display2.setText(String.valueOf(firstnum)+"*");
        
    }//GEN-LAST:event_jbtnmulActionPerformed

    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("/");
        display2.setText(String.valueOf(firstnum +"/"));
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("+");
        display2.setText(String.valueOf(firstnum)+"+");
    }//GEN-LAST:event_jbtnplusActionPerformed

    private void jbtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnminusActionPerformed
        // TODO add your handling code here:
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("-");
        display2.setText(String.valueOf(firstnum)+"-");
    }//GEN-LAST:event_jbtnminusActionPerformed

    private void jbtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequalActionPerformed
        // TODO add your handling code here:
        String answer;
        secondnum=Double.parseDouble(jtxtDisplay.getText());
        if(" +".equals(operations))
        {
             result=firstnum+secondnum;
            answer=String.format("% .2f" ,result);
            display2.setText(String.valueOf(firstnum) + "+"+String.valueOf(secondnum));
            jtxtDisplay.setText(answer);
        }
        else if ("-".equals(operations)){
            result=firstnum-secondnum;
            answer=String.format("%.2f", result);
             display2.setText(String.valueOf(firstnum) + "-"+String.valueOf(secondnum));
              jtxtDisplay.setText(answer);
        }
        else if ("*".equals(operations)){
             result= firstnum*secondnum;
            answer=String.format("%.2f", result);
             display2.setText(String.valueOf(firstnum) + "*"+String.valueOf(secondnum));
              jtxtDisplay.setText(answer);
        }
        else if ("/".equals(operations)){
            result= firstnum/secondnum;
            answer=String.format("%.2f", result);
             display2.setText(String.valueOf(firstnum) + "/"+String.valueOf(secondnum));
              jtxtDisplay.setText(answer);
        }
        else if ("%".equals(operations)){
           result=firstnum%secondnum;
            answer=String.format("%.2f", result);
             display2.setText(String.valueOf(firstnum) + "%"+String.valueOf(secondnum));
              jtxtDisplay.setText(answer);
        }
        else if(" x^y".equals(operations))
        {
           result=1;
            for(int i=0;i<secondnum;i++)
            {
                result=firstnum*result;
            }
            display2.setText(String.valueOf(firstnum)+"^("+String.valueOf(secondnum)+")");
            answer=String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            }
        
        
    }//GEN-LAST:event_jbtnequalActionPerformed

    private void jbtnexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexpActionPerformed
        // TODO add your handling code here:
        double ope=Double.parseDouble(jtxtDisplay.getText());
        double exp=10;
        double p;
        display2.setText("10^("+jtxtDisplay.getText()+")");
        p=Math.pow(exp,ope);
        jtxtDisplay.setText("");
        jtxtDisplay.setText(jtxtDisplay.getText()+p);
       
    }//GEN-LAST:event_jbtnexpActionPerformed

    private void jbtnacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnacActionPerformed
        // TODO add your handling code here:
        display2.setText("");
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jbtnacActionPerformed

    private void jbtndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndelActionPerformed
        // TODO add your handling code here:
        String del=null;
        if(jtxtDisplay.getText().length()>0)
        {
            StringBuilder strB= new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length()-1);
            del=strB.toString();
            jtxtDisplay.setText(del);
            
        }
    }//GEN-LAST:event_jbtndelActionPerformed

    private void jbtnsqrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsqrootActionPerformed
        // TODO add your handling code here:
        double ope=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText("√("+jtxtDisplay.getText()+")");
        ope=Math.sqrt(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jbtnsqrootActionPerformed

    private void jbtncbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncbrActionPerformed
        // TODO add your handling code here:
         double ope=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText("cbrt("+jtxtDisplay.getText()+")");
        ope=Math.cbrt(ope);
        jtxtDisplay.setText(String.valueOf(ope));
                                              
    }//GEN-LAST:event_jbtncbrActionPerformed

    private void jbtnrndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrndActionPerformed
        // TODO add your handling code here:
         double ope=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText("Round("+jtxtDisplay.getText()+")");
        ope=Math.round(ope);
        jtxtDisplay.setText(String.valueOf(ope));
                                              
    }//GEN-LAST:event_jbtnrndActionPerformed

    private void jbtnbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbinActionPerformed
        // TODO add your handling code here:
       int a= Integer.parseInt(jtxtDisplay.getText());
       display2.setText("Bin("+Integer.toString(a)+")");
       jtxtDisplay.setText(Integer.toString(a,2));
    }//GEN-LAST:event_jbtnbinActionPerformed

    private void jbtnoctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoctActionPerformed
        // TODO add your handling code here:
          int a= Integer.parseInt(jtxtDisplay.getText());
       display2.setText("Oct("+Integer.toString(a)+")");
       jtxtDisplay.setText(Integer.toString(a,8));
    }//GEN-LAST:event_jbtnoctActionPerformed

    private void jbtnhexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnhexActionPerformed
        // TODO add your handling code here:
          int a= Integer.parseInt(jtxtDisplay.getText());
       display2.setText("Hex("+Integer.toString(a)+")");
       jtxtDisplay.setText(Integer.toString(a,16));
    }//GEN-LAST:event_jbtnhexActionPerformed

    private void jbtnfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfactActionPerformed
        // TODO add your handling code here:
        double ope= Double.parseDouble(jtxtDisplay.getText());
        double fact=1;
        display2.setText(jtxtDisplay.getText()+"!");
        while(ope!=0)
        {
            fact=fact*ope;
            ope--;
        }
        jtxtDisplay.setText("");
        jtxtDisplay.setText(jtxtDisplay.getText()+fact);
        
    }//GEN-LAST:event_jbtnfactActionPerformed

    private void jbtnpieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpieActionPerformed
        // TODO add your handling code here:
        double a;
        double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ope=Math.PI;
        a=Double.parseDouble(String.valueOf(jtxtDisplay.getText()))*ope;
        jtxtDisplay.setText(String.valueOf(a));
    }//GEN-LAST:event_jbtnpieActionPerformed

    private void jbtnmodulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodulusActionPerformed
        // TODO add your handling code here:
        firstnum=Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("%");
        display2.setText(String.valueOf(firstnum)+"%");
    }//GEN-LAST:event_jbtnmodulusActionPerformed

    private void jbtnsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsinhActionPerformed
        // TODO add your handling code here:
        double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText("sinh("+String.valueOf(ope)+")");
        ope=Math.sinh(ope);
        jtxtDisplay.setText(String.valueOf(ope));
        
        
    }//GEN-LAST:event_jbtnsinhActionPerformed

    private void jbtncoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncoshActionPerformed
        // TODO add your handling code here:
          double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText("cosh("+String.valueOf(ope)+")");
        ope=Math.cosh(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jbtncoshActionPerformed

    private void jbtntanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntanhActionPerformed
        // TODO add your handling code here:
          double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText("tanh("+String.valueOf(ope)+")");
        ope=Math.tanh(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jbtntanhActionPerformed

    private void jbtnxpoweryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxpoweryActionPerformed
    // TODO add your handling code here:
    firstnum = Double.parseDouble(jtxtDisplay.getText());
        
        jtxtDisplay.setText(null);
    operations = "x^y";
        display2.setText(String.valueOf(firstnum)+"^(");
        
    }//GEN-LAST:event_jbtnxpoweryActionPerformed

    private void jbtnexpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexpoActionPerformed
        // TODO add your handling code here:
        double ope= Math.exp(Double.parseDouble(jtxtDisplay.getText()));
        display2.setText("e^("+jtxtDisplay.getText()+")");
        jtxtDisplay.setText("");
        jtxtDisplay.setText(jtxtDisplay.getText()+ope);
        
    }//GEN-LAST:event_jbtnexpoActionPerformed

    private void jbtnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogActionPerformed
        // TODO add your handling code here:
         double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText("log("+String.valueOf(ope)+")");
        ope=Math.log10(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jbtnlogActionPerformed

    private void jbtnlnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlnxActionPerformed
        // TODO add your handling code here:
         double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText("ln("+String.valueOf(ope)+")");
        ope=Math.log(ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jbtnlnxActionPerformed

    private void jbtnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsinActionPerformed
        // TODO add your handling code here:
        double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        if(!Shif)
        {
            if(!degrad)
            {
                display2.setText("sin("+String.valueOf(ope)+")");
                ope=ope*0.0174532925;
            }
            ope=Math.sin(ope);
        }
        else{
            display2.setText("sin^-1("+String.valueOf(ope)+")");
            ope=Math.asin(ope)/0.0174532925;
        }
        jtxtDisplay.setText(String.valueOf(ope));   
    }//GEN-LAST:event_jbtnsinActionPerformed

    private void jbtncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncosActionPerformed
        // TODO add your handling code here:
         double ope =Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
   
        if(!Shif)
        {
            if(!degrad)
            {
                display2.setText("cos("+String.valueOf(ope)+")");
                ope=ope*0.0174532925;
            }
            ope=Math.cos(ope);
        }
        else{
            display2.setText("cos^-1("+String.valueOf(ope)+")");
            ope=Math.acos(ope)/0.0174532925;
        }
        jtxtDisplay.setText(String.valueOf(ope)); 
    }//GEN-LAST:event_jbtncosActionPerformed

    private void jbtnxpower2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxpower2ActionPerformed
        // TODO add your handling code here:
        double ope=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        display2.setText(String.valueOf(jtxtDisplay.getText())+"^2");
        ope=(ope *ope);
        jtxtDisplay.setText(String.valueOf(ope));
    }//GEN-LAST:event_jbtnxpower2ActionPerformed

    private void jbtnonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnonActionPerformed
        // TODO add your handling code here:
        jbtn0.setEnabled(true);
    jbtn1.setEnabled(true);
    jbtn2.setEnabled(true);
    jbtn3.setEnabled(true);
     jbtn4.setEnabled(true);
    jbtn5.setEnabled(true);
    jbtn6.setEnabled(true);
     jbtn7.setEnabled(true);
     jbtn8.setEnabled(true);
   jbtn9.setEnabled(true);
     jbtnac.setEnabled(true);
     jbtnbin.setEnabled(true);
    jbtncbr.setEnabled(true);
    jbtncos.setEnabled(true);
     jbtncosh.setEnabled(true);
     jbtndel.setEnabled(true);
     jbtndiv.setEnabled(true);
    jbtndot.setEnabled(true);
     jbtnequal.setEnabled(true);
    jbtnexp.setEnabled(true);
    jbtnexp.setEnabled(true);
   jbtnfact.setEnabled(true);
   jbtnhex.setEnabled(true);
     jbtnlnx.setEnabled(true);
   jbtnlog.setEnabled(true);
    jbtnminus.setEnabled(true);
     jbtnmodulus.setEnabled(true);
     jbtnmul.setEnabled(true);
    jbtnoct.setEnabled(true);
     jbtnon.setEnabled(true);
     jbtnpie.setEnabled(true);
     jbtnplminus.setEnabled(true);
     jbtnplus.setEnabled(true);
  jbtnrnd.setEnabled(true);
    jbtnshift.setEnabled(true);
     jbtnsin.setEnabled(true);
    jbtnsinh.setEnabled(true);
     jbtnsqroot.setEnabled(true);
    jbtntan.setEnabled(true);
    jbtntanh.setEnabled(true);
    jbtnxpower2.setEnabled(true);
     jbtnxpower3.setEnabled(true);
     jbtnxpowery.setEnabled(true);
     jtxtDisplay.setEnabled(true);
     display2.setEnabled(true);
    }//GEN-LAST:event_jbtnonActionPerformed

    private void jbtnDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDegreeActionPerformed
        // TODO add your handling code here:
        degrad=false;
    }//GEN-LAST:event_jbtnDegreeActionPerformed

    private void jbtnRadianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRadianActionPerformed
        // TODO add your handling code here:
        degrad=true;
    }//GEN-LAST:event_jbtnRadianActionPerformed

    private void display2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display2ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scientificcalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scientificcalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scientificcalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scientificcalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scientificcalci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField display2;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JRadioButton jbtnDegree;
    private javax.swing.JRadioButton jbtnRadian;
    private javax.swing.JButton jbtnac;
    private javax.swing.JButton jbtnbin;
    private javax.swing.JButton jbtncbr;
    private javax.swing.JButton jbtncos;
    private javax.swing.JButton jbtncosh;
    private javax.swing.JButton jbtndel;
    private javax.swing.JButton jbtndiv;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtnequal;
    private javax.swing.JButton jbtnexp;
    private javax.swing.JButton jbtnexpo;
    private javax.swing.JButton jbtnfact;
    private javax.swing.JButton jbtnhex;
    private javax.swing.JButton jbtnlnx;
    private javax.swing.JButton jbtnlog;
    private javax.swing.JButton jbtnminus;
    private javax.swing.JButton jbtnmodulus;
    private javax.swing.JButton jbtnmul;
    private javax.swing.JButton jbtnoct;
    private javax.swing.JRadioButton jbtnoff;
    private javax.swing.JRadioButton jbtnon;
    private javax.swing.JButton jbtnpie;
    private javax.swing.JButton jbtnplminus;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JButton jbtnrnd;
    private javax.swing.JButton jbtnshift;
    private javax.swing.JButton jbtnsin;
    private javax.swing.JButton jbtnsinh;
    private javax.swing.JButton jbtnsqroot;
    private javax.swing.JButton jbtntan;
    private javax.swing.JButton jbtntanh;
    private javax.swing.JButton jbtnxpower2;
    private javax.swing.JButton jbtnxpower3;
    private javax.swing.JButton jbtnxpowery;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
